/**
 * Índice de invitados con video publicado (diseño 3a/3b, Claude Design).
 *
 * Nombre y cantidad de videos del canal @produccionesD10 en que aparece cada
 * uno, tal como los relevó el canvas. 299 nombres. No reemplaza a la
 * colección `invitados`: esa sólo tiene a quienes ya tienen piezas cargadas en
 * el sitio (y ficha propia). Acá entran también los que todavía no.
 *
 * Los nombres van tal cual vienen del canal, con sus tildes faltantes. Se
 * corrigen acá, no en la página.
 * TODO: dato pendiente del cliente — confirmar el listado contra el archivo.
 */
export type EntradaDelIndice = readonly [nombre: string, videos: number];

export const indiceDeInvitados: readonly EntradaDelIndice[] = [
  ['"Chifle" Molina', 2],
  ['"Conejo" Pintos', 1],
  ['"Pitufo" Lombardo', 2],
  ['Abigail Pereira', 1],
  ['Adriana Savio', 1],
  ['Alberto Sonsol', 1],
  ['Ale Bus', 2],
  ['Alejandra Díaz', 4],
  ['Alejandro "Lali" Sonsol', 1],
  ['Alejandro Astesiano', 1],
  ['Alejandro Barrere', 2],
  ['Alejandro Jasa', 1],
  ['Alejandro Martínez', 2],
  ['Alejandro Quintino', 5],
  ['Alejandro Valenzuela', 1],
  ['Alexei Yaquimenko', 2],
  ['Alfredo García', 1],
  ['Alfredo Leirós', 4],
  ['Alicia Álvarez', 1],
  ['Alvaro Padin', 1],
  ['Ana Laura Barreto', 1],
  ['Andrea Bañuls', 1],
  ['Andrea Rodriguez', 1],
  ['Andrés Abt', 1],
  ['Andrés Barrera', 2],
  ['Andrés Ojeda', 2],
  ['Anita Valiente', 1],
  ['Anita y Ellos', 1],
  ['Araceli Souza', 1],
  ['Ariana Hurtado', 1],
  ['Banda Gualicho', 2],
  ["Banda Reb'lación", 1],
  ['Banda Stainless', 1],
  ['Bashe', 1],
  ['Bettiana Diaz', 1],
  ['Braulio Assanelli', 1],
  ['Byenzo', 1],
  ['Carla Lorenzo', 2],
  ['Carlos "Bocha" Pintos', 3],
  ['Carlos Alberto Rodríguez', 3],
  ['Carlos Barceló', 2],
  ['Carlos Fernandez', 1],
  ['Carlos Goberna Jr.', 4],
  ['Carlos Hernández', 1],
  ['Carlos Leite', 1],
  ['Carlos Moreira', 1],
  ['Carlos Muñoz', 1],
  ['Carlos Nípoli', 1],
  ['Carlos Rodriguez', 1],
  ['Carmen Morán', 1],
  ['Carolina Cosse', 1],
  ['Carolina Rodriguez', 1],
  ['Carrasco', 1],
  ['Cecilia Comunales', 1],
  ['Charly Sosa', 1],
  ['Charly Álvarez', 2],
  ['Chris Namus', 2],
  ['Cintia Caballero', 1],
  ['Claudia Fernandez', 2],
  ['Claudio Martin', 1],
  ['Cliff Morgan', 2],
  ['Coco Echagüe', 1],
  ['Coco Rivero', 1],
  ['Conrado Rodríguez', 3],
  ['Constanza Moreira', 1],
  ['Corina Lawrence', 1],
  ['Cuarto Enredo', 1],
  ['César "Tola" Antúnez', 6],
  ['Dani Umpi', 2],
  ['Daniel "Kimba" Pintos', 1],
  ['Daniel Baldi', 3],
  ['Daniel Chasquetti', 1],
  ['Daniel Franco', 1],
  ['Diego Delgrossi', 1],
  ['Diego Iraola', 1],
  ['Diego Kuropatwa', 3],
  ['Dito Galeano', 4],
  ['Douglas Vazquez', 1],
  ['Dra. Andrea Ramírez Ponzo', 1],
  ['Duo Sin Fronteras', 1],
  ['Dúo Copla Alta', 1],
  ['Dúo Sandú', 1],
  ['Edgardo Martirena', 3],
  ['Edgardo Nieves', 1],
  ['Edgardo Ortuño', 1],
  ['Eduardo "Pato" Molina', 3],
  ['Eduardo Acevedo', 2],
  ['Eduardo Cerveri', 1],
  ['Eduardo Espinel', 3],
  ['Eduardo Gutiérrez', 3],
  ['El Guapo Malavia', 1],
  ['Elisa Areán', 1],
  ['Emilio Pérez', 1],
  ['Enrique Peña', 2],
  ['Eruca Sativa', 1],
  ['Eunice Castro', 1],
  ['Fabián Marquisio', 1],
  ['Fabrizio Patritti', 1],
  ['Felipe Schipani', 4],
  ['Fernando "Tololo" Serra', 1],
  ['Fernando Cristino', 1],
  ['Fernando Tetes', 3],
  ['Fernando Vilar', 3],
  ['Fernando de Moraes', 1],
  ['Fito Galli', 5],
  ['Francisco Igarza', 1],
  ['Fulana de Val', 1],
  ['Fátima Flóres', 2],
  ['Gabriel Buonagura', 1],
  ['Gabriel Parma', 2],
  ['Gabriela Irribarren', 1],
  ['Gabriela Montenegro', 5],
  ['Garo Arakelian', 1],
  ['Gaspar Valverde', 1],
  ['Gastón "Rusito" González', 2],
  ['Gastón Da Cruz', 5],
  ['Gerardo de Dominicis', 1],
  ['Germán Bernardez', 1],
  ['Gonzalo "El Pela" Romero', 2],
  ['Gonzalo Bauza', 1],
  ['Gonzalo Halty', 3],
  ['Guille Taranto', 2],
  ['Guillermo Almada', 1],
  ['Guillermo Rodríguez', 2],
  ['Gustavo Bianchi', 1],
  ['Gustavo Salle', 8],
  ['Gustavo Álvarez', 8],
  ['Habibi', 4],
  ['Horacio Ascheri', 1],
  ['Horacio Rubino', 5],
  ['Hugo Cachés "Pola"', 1],
  ['Humberto de Vargas', 1],
  ['Ignacio Durán', 1],
  ['Ines Monzillo', 1],
  ['Iza el Alma', 1],
  ['Javier Mas', 1],
  ['Javier Pacheco', 1],
  ['Jazmin Briguez', 1],
  ['Jeff Granger', 1],
  ['Jimmy Castilhos', 1],
  ['Jonathan López', 1],
  ['Jorge "Carna" Crivelli', 1],
  ['Jorge "Superman" Seré', 2],
  ['Jorge "Toto" Da Silveira', 2],
  ['Jorge Baillo', 1],
  ['Jorge Bermúdez', 1],
  ['Jorge Bonica', 5],
  ['Jorge Gandini', 4],
  ['Jorge Pintos "Bafo"', 2],
  ['Jorge Torres', 3],
  ['Jose María Muscari', 1],
  ['Joselo Romero', 1],
  ['José Lorca', 1],
  ['José Luis Bringa', 2],
  ['Juan Carlos Scelza', 1],
  ['Juan Ceretta', 1],
  ['Juan Granato', 4],
  ['Juan Mariño', 1],
  ['Juan Perdomo', 1],
  ['Juan Rodriguez Puppo', 1],
  ['Julio "Bicho" Yuane', 1],
  ['Karina Nuñez', 1],
  ['Karina Videla', 1],
  ['Karina Vignola', 1],
  ['Katherine Sierra', 1],
  ['Las Pantuflas Cósmicas', 1],
  ['Las Queridas', 1],
  ['Laura Raffo', 2],
  ['Leo Carlini', 4],
  ['Leo Pacella', 1],
  ['Leo Ramos', 1],
  ['Liliam Kechichian', 1],
  ['Lisandro Flores', 1],
  ['Lola Moreira', 1],
  ['Lolo Viña y Steve Carbajal', 1],
  ['Los Casal', 1],
  ['Los Giles Montevideanos', 1],
  ['Luana Trillo y Constanza Ripoll', 1],
  ['Lucrecia', 1],
  ['Lucy y Cristian', 1],
  ['Lucía Acuña', 1],
  ['Luigi Mega', 1],
  ['Luis Orpi', 5],
  ['Mago Ariel', 4],
  ['Manu Merli', 1],
  ['Marcel Keoroglian', 4],
  ['Marcel Lhermitte y Sebastian Chittadini', 1],
  ['Marcel Mantero', 2],
  ['Marcelo Appolonia', 1],
  ['Marcelo Areco', 1],
  ['Marcelo Capalbo', 1],
  ['Marcos da Costa', 1],
  ['Maria Alejandra Jaimes', 1],
  ['Maria Boccone', 1],
  ['Maria Clara Vazquez', 1],
  ['Mariano Bermudez', 2],
  ['Mariné Guerrero', 1],
  ['Mario Bergara', 3],
  ['Mario Erramuspe y Laura Ruggiero', 1],
  ['Marisa Perez', 1],
  ['Marlons Rock', 1],
  ['Marta Gonzalez', 1],
  ['Martin Frustaci', 1],
  ['Martin Lasarte', 1],
  ['Martin Piña', 1],
  ['Martín Alvarez', 1],
  ['Martín Sandoval', 2],
  ['Martín de Freitas', 1],
  ['María Julia Muñoz', 3],
  ['María Mendendez', 1],
  ['María de Lima', 2],
  ['Matías Valdez', 1],
  ['Mauricio Etchenique', 4],
  ['Maxi Pérez', 1],
  ['Maya Landesman', 1],
  ['Miguel Asqueta', 1],
  ['Miguel Bestard', 2],
  ['Miguel Raffi', 1],
  ['Miguel Ángel Cufós', 6],
  ['Modo Cumbia', 1],
  ["Molina L'Autentika", 1],
  ['Monica Navarro', 1],
  ['Mónica Ramirez', 1],
  ['Mónica Santos', 1],
  ['Nacho Delgado', 1],
  ['Nacho Rius', 2],
  ['Nadia Valverde', 1],
  ['Natalia Camilo', 1],
  ['Natalia Roman', 1],
  ['Natalia Ruiz Díaz', 3],
  ['Nelson Burgos', 4],
  ['Nelson Pino', 4],
  ['Nico Lanz', 1],
  ['Nicolas Quintana', 1],
  ['Niusa Samba', 1],
  ['Noelia Etcheverry', 1],
  ['Obdulio Trasante', 2],
  ['Oscar Andrade', 1],
  ['Pablo Aguirrezabal', 1],
  ['Pablo Cabrera', 1],
  ['Pablo Cocina', 3],
  ['Pablo Fraga', 1],
  ['Pablo Iturralde', 1],
  ['Pablo Oyhenart', 2],
  ['Pae Donato', 1],
  ['Paola Lo', 1],
  ['Patricia Izuibejeres', 1],
  ['Patricia Pita', 1],
  ['Patricia Rodriguez', 1],
  ["Pecho E' Fierro", 3],
  ['Petru Valensky', 3],
  ['Rafael Michelini', 3],
  ['Raul Abirad', 1],
  ['Raúl Menéndez', 2],
  ['Ricardo Alarcón', 1],
  ['Ricardo Méndez', 1],
  ['Richard Núñez', 3],
  ['Richard Read', 6],
  ['Rigo Rioja', 1],
  ['Robert Moré', 1],
  ['Robert Silva', 2],
  ['Roberto Orrego', 1],
  ['Rodolfo Kunin', 1],
  ['Rodrigo Goñi', 2],
  ['Rodrigo Lopez', 1],
  ['Rogelio Gracia', 1],
  ['Rosina Benenati', 2],
  ['Sandra Batolomeo', 1],
  ['Sandra Marcos', 4],
  ['Sandra Salamo', 1],
  ['Santiago Gonzalez', 2],
  ['Santiago Tricánico', 4],
  ['Sebastián Manito', 1],
  ['Sergio Botana', 1],
  ['Sergio Gorzy', 1],
  ['Sergio Secinaro', 3],
  ['Sergio Silvestri', 1],
  ['Sergio Sosa', 2],
  ['Shuggar', 1],
  ['Simplemente Luis', 1],
  ['Sofía León', 1],
  ['Solange', 3],
  ['Sonora Palacio', 5],
  ['Spuntone & Mendaro', 1],
  ['Susana Andrade', 5],
  ['Sylvia Mediondo', 2],
  ['Tomás Pedetti', 1],
  ['Valentina Martinez', 1],
  ['Varina de Cesare', 1],
  ['Victoria Rodríguez', 2],
  ['Victoria Sagasti', 1],
  ['Virginia Ramos', 1],
  ['Walter Godoy', 2],
  ['Wosh Machín', 2],
  ['Yessy López', 2],
  ['Álvaro González Márquez', 1],
  ['Álvaro Santana', 1],
  ['Álvaro Viviano', 1],
  ['Ángeles Lasso', 1],
];
